"""
Adversarial failing tests for the six safety/honesty gaps in JARVIS Engineering Intelligence.

These tests prove the bugs described in docs/PROJECT_STATE.md. Every test is
currently EXPECTED TO FAIL. Do not edit this file to make it pass - fix src/.

Gap 1: Library-level personal-root protection is not fail-closed enough.
Gap 2: Secret redaction is too weak for real committed repositories.
Gap 3: Change-impact and dependency reasoning are accepted but not implemented.
Gap 4: Relevance scoring can drop ADR evidence when another file overlaps more.
Gap 5: Evidence bounds make "unknown" ambiguous between not-found and not-inspected.
Gap 6: Benchmark expectations have no runner and include behavior v1 cannot deliver.
"""
from __future__ import annotations

import json
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = PROJECT_ROOT / "src"
FIXTURE_ROOT = PROJECT_ROOT / "tests" / "fixtures" / "sample_repo"

import sys
sys.path.insert(0, str(SRC_ROOT))

from jarvis_engineering.contracts import ErrorCode, InspectionError, InspectionLimits
from jarvis_engineering.inspector import inspect_repository


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

def _git(repository: Path, *arguments: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(repository), *arguments],
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def _make_repo(root: Path, name: str, remote: str) -> Path:
    """Create and initialise a git repo under root/name with origin set to remote."""
    checkout = root / name
    checkout.mkdir(parents=True)
    _git(checkout, "init", "-q")
    _git(checkout, "config", "user.email", "tests@example.com")
    _git(checkout, "config", "user.name", "JARVIS Tests")
    _git(checkout, "remote", "add", "origin", remote)
    return checkout


def _commit(checkout: Path, files: dict[str, str]) -> None:
    """Write files to the checkout and create a commit."""
    for path_str, content in files.items():
        dest = checkout / path_str
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
    _git(checkout, "add", ".")
    _git(checkout, "commit", "-qm", "fixture")


# ---------------------------------------------------------------------------
# Gap 1: fail-closed protected_root behavior
# ---------------------------------------------------------------------------

class ProtectedRootTests(unittest.TestCase):
    """
    Gap: protected_root=None is fail-open. The protection opt-in default silently
    disables all personal-root isolation when callers omit the argument.
    """

    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory()
        self.root = Path(self.temp.name)
        self.checkout = _make_repo(
            self.root, "sample", "https://github.com/example/checkout-service.git"
        )
        _commit(self.checkout, {"README.md": "# Sample\nThis is a sample repository.\n"})

    def tearDown(self) -> None:
        self.temp.cleanup()

    def test_no_protected_root_must_be_fail_closed(self) -> None:
        """
        CURRENTLY FAILS: protected_root=None silently allows all checkouts.

        A fail-closed system must refuse to operate when the personal-root
        protection is unconfigured. The caller must explicitly opt OUT of
        protection, not opt IN. Without this, any caller who forgets the
        argument gets zero isolation enforcement.

        Source defect: isolation.py resolve_target() skips the entire
        protected-root check when protected_root is None (line 135).
        inspect_repository() defaults protected_root=None (inspector.py line 78).
        """
        with self.assertRaises(InspectionError) as caught:
            inspect_repository(
                "https://github.com/example/checkout-service",
                "sample",
                str(self.root),
                "What is the architecture?",
                # protected_root intentionally omitted — the default None must not be fail-open
            )
        self.assertIn(
            caught.exception.code,
            {ErrorCode.PROTECTED_ROOT_ACCESS, ErrorCode.INSPECTION_FAILED},
            msg=(
                "protected_root=None must fail-closed, but inspect_repository succeeded "
                "and returned a report. Any caller who forgets protected_root bypasses "
                "all personal-root isolation."
            ),
        )

    def test_checkout_under_brain_named_parent_blocked_without_explicit_protected_root(
        self,
    ) -> None:
        """
        CURRENTLY FAILS: a checkout inside a path that looks like a personal root
        (e.g. under a directory named 'brain') is accepted when protected_root=None.

        Without a hardcoded or configured default, the name of the directory is
        never checked. Any path is permitted.

        Source defect: same as above — the guard at isolation.py:135 is not reached.
        """
        personal_root = self.root / "brain"
        personal_root.mkdir()
        personal_checkout = _make_repo(
            personal_root, "sample", "https://github.com/example/checkout-service.git"
        )
        _commit(personal_checkout, {"README.md": "# Personal\nPersonal repo.\n"})

        with self.assertRaises(InspectionError) as caught:
            inspect_repository(
                "https://github.com/example/checkout-service",
                str(personal_checkout),
                str(personal_root),
                "What is the architecture?",
                # protected_root intentionally omitted
            )
        self.assertEqual(
            caught.exception.code,
            ErrorCode.PROTECTED_ROOT_ACCESS,
            msg=(
                "A checkout inside a 'brain'-named directory must be rejected even "
                "when protected_root is not explicitly passed. Currently succeeds."
            ),
        )


# ---------------------------------------------------------------------------
# Gap 2: committed secret redaction
# ---------------------------------------------------------------------------

class SecretRedactionTests(unittest.TestCase):
    """
    Gap: _SECRET_RE in evidence.py only matches a narrow set of key-name patterns
    at the start of a line with no prefix. Real repositories commit secrets in
    JSON format, with 'export' prefixes, or with key names outside the pattern.
    """

    REMOTE = "https://github.com/example/checkout-service.git"
    URL = "https://github.com/example/checkout-service"

    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory()
        self.root = Path(self.temp.name)
        self.checkout = _make_repo(self.root, "sample", self.REMOTE)

    def tearDown(self) -> None:
        self.temp.cleanup()

    def _get_all_excerpts(self, files: dict[str, str], question: str) -> str:
        """Commit files, inspect, and return all evidence excerpts joined."""
        _commit(self.checkout, files)
        report = inspect_repository(
            self.URL,
            "sample",
            str(self.root),
            question,
            protected_root=PROJECT_ROOT.parent,
        )
        return "\n".join(item["excerpt"] for item in report["evidence"])

    def test_json_format_secret_is_redacted(self) -> None:
        """
        CURRENTLY FAILS: a JSON-format secret like `"api_key": "sk_live_abc"` is not
        redacted. _SECRET_RE requires the key name to start the line without quotes,
        so the leading `"` in JSON causes the match to fail.

        Source defect: evidence.py _SECRET_RE (line 53) pattern anchors with
        optional whitespace then the key name. The leading `"` in JSON format
        sits between the whitespace and the key, breaking the match.
        """
        excerpts = self._get_all_excerpts(
            {
                "settings.json": (
                    '{\n'
                    '  "api_key": "sk_live_supersecretvalue123",\n'
                    '  "environment": "production"\n'
                    '}\n'
                )
            },
            "What is the service configuration?",
        )
        self.assertNotIn(
            "sk_live_supersecretvalue123",
            excerpts,
            msg=(
                "JSON-format api_key value must be redacted in evidence excerpts. "
                "Currently appears verbatim because _SECRET_RE does not match "
                'the leading `"` of JSON key names.'
            ),
        )

    def test_export_prefixed_secret_is_redacted(self) -> None:
        """
        CURRENTLY FAILS: `export SECRET_KEY=value` is not redacted. The `export`
        prefix sits between the start-of-line anchor and the key name, breaking
        the match. Shell config files commonly use this pattern.

        Source defect: evidence.py _SECRET_RE does not account for `export` prefix.
        """
        excerpts = self._get_all_excerpts(
            {
                "config.sh": (
                    "#!/bin/bash\n"
                    "# Application runtime configuration\n"
                    "export SECRET_KEY=supersecretproductionkey\n"
                    "export DATABASE_URL=postgres://user:pass@host/db\n"
                )
            },
            "What is the service configuration?",
        )
        self.assertNotIn(
            "supersecretproductionkey",
            excerpts,
            msg=(
                "export SECRET_KEY value must be redacted. Currently appears because "
                "_SECRET_RE cannot match lines starting with 'export '."
            ),
        )

    def test_stripe_key_pattern_is_redacted(self) -> None:
        """
        CURRENTLY FAILS: `STRIPE_SECRET_KEY = 'sk_live_...'` is not redacted.
        The key name 'STRIPE_SECRET_KEY' is not in _SECRET_RE's explicit list, and
        even though it contains 'SECRET', the full pattern requires the key name
        to match one of the listed alternatives exactly.

        Source defect: evidence.py _SECRET_RE lists only a fixed set of key names
        (api_key, access_token, auth_token, client_secret, password, private_key,
        secret). Compound names like STRIPE_SECRET_KEY are not matched.
        """
        excerpts = self._get_all_excerpts(
            {
                "config/payments.py": (
                    "# Payment gateway configuration\n"
                    "STRIPE_SECRET_KEY = 'sk_live_reallyimportantsecret'\n"
                    "STRIPE_PUBLISHABLE_KEY = 'pk_live_public'\n"
                )
            },
            "What is the architecture of payments?",
        )
        self.assertNotIn(
            "sk_live_reallyimportantsecret",
            excerpts,
            msg=(
                "STRIPE_SECRET_KEY value must be redacted. Currently appears because "
                "'STRIPE_SECRET_KEY' is not in _SECRET_RE's key-name alternatives."
            ),
        )

    def test_aws_credentials_are_redacted(self) -> None:
        """
        CURRENTLY FAILS: AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are not
        matched by _SECRET_RE. These are among the most dangerous secrets to
        expose; they are also among the most commonly committed.

        Source defect: 'aws_access_key_id' and 'aws_secret_access_key' are absent
        from the evidence.py _SECRET_RE pattern list.
        """
        excerpts = self._get_all_excerpts(
            {
                "infra/deploy.sh": (
                    "#!/bin/bash\n"
                    "# Deployment credentials — do not share\n"
                    "AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE\n"
                    "AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY\n"
                )
            },
            "What is the deployment configuration?",
        )
        self.assertNotIn(
            "AKIAIOSFODNN7EXAMPLE",
            excerpts,
            msg="AWS_ACCESS_KEY_ID value must be redacted but appears in deployment evidence.",
        )
        self.assertNotIn(
            "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
            excerpts,
            msg="AWS_SECRET_ACCESS_KEY value must be redacted but appears in deployment evidence.",
        )

    def test_github_token_is_redacted(self) -> None:
        """
        CURRENTLY FAILS: `github_token: ghp_...` in a CI workflow is not redacted.
        'github_token' does not appear in _SECRET_RE's key-name list. CI workflow
        files are classified and collected, so the token is exposed verbatim.

        Source defect: evidence.py _SECRET_RE omits 'github[_-]?token'.
        """
        excerpts = self._get_all_excerpts(
            {
                ".github/workflows/ci.yml": (
                    "name: CI\n"
                    "on: [push]\n"
                    "jobs:\n"
                    "  build:\n"
                    "    runs-on: ubuntu-latest\n"
                    "    env:\n"
                    "      github_token: ghp_realTokenValueHere123\n"
                    "    steps:\n"
                    "      - uses: actions/checkout@v3\n"
                )
            },
            "What is the CI configuration?",
        )
        self.assertNotIn(
            "ghp_realTokenValueHere123",
            excerpts,
            msg=(
                "github_token value must be redacted in CI evidence. Currently appears "
                "because 'github_token' is not in _SECRET_RE's key-name alternatives."
            ),
        )


# ---------------------------------------------------------------------------
# Gap 3: unsupported change-impact and dependency questions
# ---------------------------------------------------------------------------

class UnsupportedQuestionTests(unittest.TestCase):
    """
    Gap: change-impact and dependency questions pass _question_tokens validation
    and return generic evidence reports. The product cannot perform this analysis;
    it must refuse rather than silently return misleading partial results.
    """

    REMOTE = "https://github.com/example/checkout-service.git"
    URL = "https://github.com/example/checkout-service"

    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory()
        self.root = Path(self.temp.name)
        self.checkout = _make_repo(self.root, "sample", self.REMOTE)
        _commit(self.checkout, {
            "README.md": "# Service\nCheckout service handles orders.\n",
            "src/service.py": "class CheckoutService:\n    pass\n",
        })

    def tearDown(self) -> None:
        self.temp.cleanup()

    def _inspect(self, question: str) -> dict:
        return inspect_repository(
            self.URL,
            "sample",
            str(self.root),
            question,
            protected_root=PROJECT_ROOT.parent,
        )

    def test_change_impact_question_is_rejected_as_unsupported(self) -> None:
        """
        CURRENTLY FAILS: "What is the impact of changing the event bus?" passes
        _question_tokens (because 'impact' is in _QUESTION_TERMS) and returns a
        generic evidence report. The product has no impact analysis; accepting
        this question produces a misleading output.

        Source defect: inspector.py _question_tokens does not detect or reject
        impact/dependency phrasing; inspect_repository returns generic results.
        """
        with self.assertRaises(InspectionError) as caught:
            self._inspect("What is the impact of changing the event bus?")
        self.assertEqual(
            caught.exception.code,
            ErrorCode.UNSUPPORTED_QUESTION,
            msg=(
                "Change-impact questions must be rejected with UNSUPPORTED_QUESTION. "
                "Currently the call succeeds and returns generic evidence, implying "
                "the product performed impact analysis it cannot actually do."
            ),
        )

    def test_dependency_tracing_question_is_rejected_as_unsupported(self) -> None:
        """
        CURRENTLY FAILS: "Which services depend on the checkout API?" passes
        validation (len(tokens) >= 2 satisfies the check) and returns generic
        evidence. Dependency-graph tracing is not implemented; accepting the
        question creates false confidence in the answer.

        Source defect: inspector.py _question_tokens only requires 2 tokens or
        a term from _QUESTION_TERMS; it never detects dependency-reasoning scope.
        """
        with self.assertRaises(InspectionError) as caught:
            self._inspect("Which services depend on the checkout API?")
        self.assertEqual(
            caught.exception.code,
            ErrorCode.UNSUPPORTED_QUESTION,
            msg=(
                "Dependency-tracing questions must be rejected with UNSUPPORTED_QUESTION. "
                "Currently succeeds and returns evidence implying dependency analysis."
            ),
        )

    def test_impact_rejection_message_names_unsupported_capability(self) -> None:
        """
        CURRENTLY FAILS: if change-impact is (eventually) rejected, the error
        message must name 'change-impact' or 'dependency' as the unsupported
        capability so callers know what class of question to avoid.

        Source defect: even if UNSUPPORTED_QUESTION were raised, the current
        generic message ("Ask an architecture, decision...") does not mention
        impact or dependency analysis.
        """
        with self.assertRaises(InspectionError) as caught:
            self._inspect("What is the impact of changing the service boundary?")
        msg = caught.exception.message.casefold()
        self.assertTrue(
            "impact" in msg or "dependency" in msg or "change" in msg,
            msg=(
                f"UNSUPPORTED_QUESTION message must name the unsupported capability. "
                f"Got: {caught.exception.message!r}"
            ),
        )


# ---------------------------------------------------------------------------
# Gap 4: ADR relevance must not be dropped by lexical overlap
# ---------------------------------------------------------------------------

class AdrRelevanceTests(unittest.TestCase):
    """
    Gap: _relevant_evidence in inspector.py returns ONLY items matching the
    highest token-overlap count. When a README or source file matches more
    question tokens than the ADR, the ADR is silently excluded from the
    findings even though it is the authoritative decision record.
    """

    REMOTE = "https://github.com/example/checkout-service.git"
    URL = "https://github.com/example/checkout-service"

    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory()
        self.root = Path(self.temp.name)
        self.checkout = _make_repo(self.root, "sample", self.REMOTE)

    def tearDown(self) -> None:
        self.temp.cleanup()

    def test_adr_cited_in_rationale_finding_when_readme_has_more_overlap(
        self,
    ) -> None:
        """
        CURRENTLY FAILS: the README is crafted to match all question tokens (overlap=7)
        while the ADR matches only 3. _relevant_evidence returns only the README.
        The ADR, which contains the explicit rationale, is excluded from relevant
        and therefore never cited in the decision+rationale observed finding.

        Source defect: inspector.py _relevant_evidence (line 68) filters to
        `overlap == strongest_overlap`, discarding all lower-overlap items including
        authoritative decision records.
        """
        # README matches all question tokens: why, did, we, decide, in-process, event, bus
        _commit(self.checkout, {
            "README.md": (
                "# Why We Decided on Event Bus\n\n"
                "We decided to use an in-process event bus. We did evaluate alternatives.\n"
                "Why? Because it decouples our services.\n"
            ),
            # ADR matches only 3 tokens (in-process, event, bus via path)
            # but IS the authoritative record with explicit decision+rationale language
            "docs/adr/0001-event-bus.md": (
                "# ADR 0001: In-Process Bus\n\n"
                "Status: Accepted\n\n"
                "## Decision\n\n"
                "Adopted an in-process message broker.\n\n"
                "## Rationale\n\n"
                "Because coupling notification failures to the purchase path was unacceptable.\n"
            ),
        })

        report = inspect_repository(
            self.URL,
            "sample",
            str(self.root),
            "Why did we decide to use an in-process event bus?",
            protected_root=PROJECT_ROOT.parent,
        )

        # The ADR must be collected as evidence
        evidence_by_path = {item["path"]: item for item in report["evidence"]}
        self.assertIn(
            "docs/adr/0001-event-bus.md",
            evidence_by_path,
            msg="ADR must be in collected evidence",
        )

        # The ADR must be cited in an 'explicitly records both' rationale finding
        rationale_findings = [
            f for f in report["findings"]["observed"]
            if "explicitly records both" in f["statement"]
        ]
        self.assertTrue(
            rationale_findings,
            msg=(
                "Must have an observed finding that explicitly records both decision "
                "and rationale. Currently absent because ADR is dropped by overlap filter."
            ),
        )
        adr_id = evidence_by_path["docs/adr/0001-event-bus.md"]["id"]
        cited_ids = {c for f in rationale_findings for c in f["citations"]}
        self.assertIn(
            adr_id,
            cited_ids,
            msg=(
                f"ADR (id={adr_id!r}) must be cited in the decision+rationale finding. "
                f"Currently excluded because README overlaps more question tokens. "
                f"Cited ids: {cited_ids}"
            ),
        )

    def test_adr_dropping_causes_false_unknown_rationale_on_why_question(
        self,
    ) -> None:
        """
        CURRENTLY FAILS: the worst symptom of the relevance bug. When the ADR is
        dropped because the README has more token overlap AND the README itself has
        no rationale language, a 'why' question produces an 'unknown rationale'
        finding even though the ADR explicitly documents the rationale.

        The product actively tells the caller the rationale is unknown, when it is
        in fact present in a collected evidence item that the relevance filter discarded.

        Source defect: inspector.py _relevant_evidence (line 68) drops the ADR;
        inspector.py line 207 then emits unknown-rationale because
        relevant_rationales is empty — not because the rationale is absent.
        """
        _commit(self.checkout, {
            # README: high overlap (did, we, decide, database = 4 tokens) but NO rationale
            "README.md": (
                "# Database Decision\n\n"
                "We decided to use PostgreSQL. We did evaluate alternatives.\n"
                "The team selected PostgreSQL for performance reasons.\n"
            ),
            # ADR: low overlap (1 token via path) but explicit decision AND rationale
            "docs/decisions/0002-database.md": (
                "# ADR 0002: Database Selection\n\n"
                "Status: Accepted\n\n"
                "## Decision\n\n"
                "Adopted PostgreSQL for its ACID transaction support.\n\n"
                "## Rationale\n\n"
                "Strong consistency required for financial records.\n"
            ),
        })

        report = inspect_repository(
            self.URL,
            "sample",
            str(self.root),
            "Why did we decide on the database?",
            protected_root=PROJECT_ROOT.parent,
        )

        # Confirm the ADR was collected and has rationale language
        adr_items = [
            item for item in report["evidence"]
            if "0002-database" in item["path"] and item["explicit_rationale_language"]
        ]
        self.assertTrue(
            adr_items,
            msg="ADR with explicit rationale must be collected as evidence.",
        )

        # The product must NOT report unknown rationale when the ADR documents it
        false_unknown_rationale = [
            f for f in report["findings"]["unknown"]
            if "rationale" in f["statement"].casefold()
        ]
        self.assertFalse(
            false_unknown_rationale,
            msg=(
                "Must not report unknown rationale when the ADR explicitly documents it. "
                "Currently the ADR is dropped by the relevance filter (README has more "
                "token overlap), so the product falsely returns 'rationale unknown'. "
                f"False unknown statements: {[f['statement'] for f in false_unknown_rationale]}"
            ),
        )


# ---------------------------------------------------------------------------
# Gap 5: bounded scan — unknown vs not-inspected
# ---------------------------------------------------------------------------

class BoundedScanAmbiguityTests(unittest.TestCase):
    """
    Gap: when evidence collection is truncated, the 'unknown rationale' finding
    is indistinguishable from 'truly searched everything and found nothing'.
    Callers cannot tell whether the answer is absent or merely uninspected.
    """

    REMOTE = "https://github.com/example/checkout-service.git"
    URL = "https://github.com/example/checkout-service"

    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory()
        self.root = Path(self.temp.name)
        self.checkout = _make_repo(self.root, "sample", self.REMOTE)
        _commit(self.checkout, {
            "README.md": "# Service\nCheckout service.\n",
            "src/a.py": "# module a\npass\n",
            "src/b.py": "# module b\npass\n",
            "src/c.py": "# module c\npass\n",
        })

    def tearDown(self) -> None:
        self.temp.cleanup()

    def _inspect_tight(self, question: str) -> dict:
        """Run with limits tight enough to guarantee truncation."""
        limits = InspectionLimits(
            max_files=1,
            max_file_bytes=131_072,
            max_total_bytes=2_097_152,
            max_tracked_paths=20_000,
            max_evidence_items=1,
            git_timeout_seconds=20,
        )
        return inspect_repository(
            self.URL,
            "sample",
            str(self.root),
            question,
            limits=limits,
            protected_root=PROJECT_ROOT.parent,
        )

    def test_truncated_rationale_unknown_must_distinguish_not_inspected(self) -> None:
        """
        CURRENTLY FAILS: when the scan is truncated AND no rationale is found,
        the 'unknown rationale' finding says nothing about the truncation. A reader
        cannot know whether the rationale is absent from the repo or simply beyond
        the scan boundary.

        A correct report must either:
        (a) qualify the finding with 'not all files were inspected', OR
        (b) use a distinct classification such as 'not_inspected'.

        Source defect: inspector.py generates the rationale-unknown finding
        (line 207) independently of the truncation-unknown finding (line 226).
        Neither references the other; the connection is invisible to the caller.
        """
        report = self._inspect_tight("Why does the checkout service exist?")

        # Verify truncation actually occurred
        self.assertTrue(
            any(
                "bounds" in w.casefold() or "capped" in w.casefold()
                for w in report["warnings"]
            ),
            msg="Expected a truncation warning from tight limits.",
        )

        # The rationale-unknown finding must acknowledge that not all files were searched
        rationale_unknowns = [
            f["statement"]
            for f in report["findings"]["unknown"]
            if "rationale" in f["statement"].casefold()
        ]
        if not rationale_unknowns:
            # No rationale-unknown emitted at all — also acceptable if truncation
            # prevents the system from knowing whether a "why" was even asked.
            # But currently the system does emit it; confirm that when it does
            # it qualifies correctly.
            return

        for statement in rationale_unknowns:
            self.assertTrue(
                any(
                    kw in statement.casefold()
                    for kw in ("not inspected", "bounds", "partial", "truncat", "within")
                ),
                msg=(
                    "When the scan is truncated, the rationale-unknown finding must "
                    "indicate that not all files were inspected. Currently states the "
                    "rationale is 'unknown' with no qualification, making it "
                    "indistinguishable from a complete scan that found nothing. "
                    f"Got: {statement!r}"
                ),
            )

    def test_report_schema_distinguishes_unknown_from_not_inspected(self) -> None:
        """
        CURRENTLY FAILS: the report schema has no field or classification to
        distinguish 'searched all files, rationale absent' from 'scan bounded,
        rationale may exist in uninspected files'. Both appear as 'unknown' with
        'low' confidence and no structural difference.

        A correct schema needs either a separate classification value
        ('not_inspected') or a boolean field on the finding linking it to the
        truncation context.

        Source defect: contracts.py Finding dataclass (line 93) has no
        'scope_limited' or 'not_inspected' field; inspector.py uses the same
        'unknown' classification for both states.
        """
        report = self._inspect_tight("Why does the checkout service exist?")

        truncation_unknowns = [
            f for f in report["findings"]["unknown"]
            if "bounds" in f["statement"].casefold() or "additional" in f["statement"].casefold()
        ]
        rationale_unknowns = [
            f for f in report["findings"]["unknown"]
            if "rationale" in f["statement"].casefold()
        ]

        if not (truncation_unknowns and rationale_unknowns):
            # If either is absent the schema gap may not be visible here,
            # but the structural link must still exist when both are present.
            return

        # The rationale-unknown must structurally reference the truncation-unknown
        # so a caller can detect the difference programmatically.
        rationale_cites_truncation = any(
            truncation_unknowns[0]["id"] in f.get("citations", [])
            for f in rationale_unknowns
        )
        rationale_qualified = any(
            "not inspected" in f["statement"].casefold()
            or "bounds" in f["statement"].casefold()
            for f in rationale_unknowns
        )
        self.assertTrue(
            rationale_cites_truncation or rationale_qualified,
            msg=(
                "When the scan is truncated, the rationale-unknown finding must "
                "either cite the truncation finding or explicitly qualify that not "
                "all files were inspected. Currently the two findings are disconnected "
                "and structurally identical to a full-scan unknown."
            ),
        )


# ---------------------------------------------------------------------------
# Gap 6: benchmark expectations ahead of v1 behavior
# ---------------------------------------------------------------------------

class BenchmarkConsistencyTests(unittest.TestCase):
    """
    Gap: benchmarks/scenarios.json defines expectations that have no programmatic
    runner. Additionally, some expectations assume capabilities (e.g. reliable ADR
    surfacing, rejection of unsupported question types) that v1 does not deliver.
    """

    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory()
        self.root = Path(self.temp.name)
        self.checkout = self.root / "sample"
        shutil.copytree(FIXTURE_ROOT, self.checkout)
        _git(self.checkout, "init", "-q")
        _git(self.checkout, "config", "user.email", "tests@example.com")
        _git(self.checkout, "config", "user.name", "JARVIS Tests")
        _git(
            self.checkout,
            "remote",
            "add",
            "origin",
            "https://github.com/example/checkout-service.git",
        )
        _git(self.checkout, "add", ".")
        _git(self.checkout, "commit", "-qm", "fixture")
        self.benchmark_path = PROJECT_ROOT / "benchmarks" / "scenarios.json"

    def tearDown(self) -> None:
        self.temp.cleanup()

    def _inspect(self, question: str) -> dict:
        return inspect_repository(
            "https://github.com/example/checkout-service",
            "sample",
            str(self.root),
            question,
            protected_root=PROJECT_ROOT.parent,
        )

    def _load_scenarios(self) -> list[dict]:
        with open(self.benchmark_path, encoding="utf-8") as fh:
            return json.load(fh)

    def test_impact_question_scenario_must_be_rejected(self) -> None:
        """
        CURRENTLY FAILS: the benchmark has no scenario for change-impact questions.
        A correctly scoped benchmark must include such a scenario and expect
        UNSUPPORTED_QUESTION. Adding one here proves v1 cannot satisfy it.

        This test acts as the missing scenario and shows v1 behavior is behind
        the benchmark's implied contract: the benchmark must grow to include
        unsupported-question coverage, and v1 must implement the rejection.
        """
        # This scenario SHOULD be in scenarios.json to protect the product boundary
        adversarial_scenario = {
            "id": "change-impact-unsupported",
            "question": "What is the impact of changing the checkout event bus?",
            "expected": {"error_code": "UNSUPPORTED_QUESTION"},
        }

        with self.assertRaises(InspectionError) as caught:
            self._inspect(adversarial_scenario["question"])
        self.assertEqual(
            caught.exception.code,
            adversarial_scenario["expected"]["error_code"],
            msg=(
                f"Scenario {adversarial_scenario['id']!r}: expected "
                f"UNSUPPORTED_QUESTION for a change-impact question, "
                f"but v1 accepted it and returned a report. "
                f"The benchmark must include this scenario and v1 must implement the rejection."
            ),
        )

    def test_all_existing_benchmark_scenarios_pass(self) -> None:
        """
        Acts as the missing benchmark runner. Validates all scenarios in
        scenarios.json against the current fixture. Any failure here means
        benchmark expectations diverge from v1 behavior.

        If this test itself passes, the runner infrastructure was missing but the
        scenarios happened to be aligned. If it fails, it identifies which
        scenario is 'ahead of v1'.
        """
        scenarios = self._load_scenarios()
        failures: list[str] = []

        for scenario in scenarios:
            sid = scenario["id"]
            question = scenario["question"]
            expected = scenario["expected"]

            try:
                if "error_code" in expected:
                    try:
                        self._inspect(question)
                        failures.append(
                            f"{sid}: expected error {expected['error_code']!r} but call succeeded"
                        )
                    except InspectionError as exc:
                        if str(exc.code) != str(expected["error_code"]):
                            failures.append(
                                f"{sid}: expected error {expected['error_code']!r} "
                                f"but got {exc.code!r}"
                            )
                    continue

                report = self._inspect(question)
                all_text = json.dumps(report)

                if "must_cite" in expected:
                    cited_paths = {item["path"] for item in report["evidence"]}
                    if expected["must_cite"] not in cited_paths:
                        failures.append(
                            f"{sid}: must_cite {expected['must_cite']!r} not in evidence paths "
                            f"{sorted(cited_paths)!r}"
                        )

                if expected.get("must_not_be_unknown"):
                    rationale_unknowns = [
                        f for f in report["findings"]["unknown"]
                        if "rationale" in f["statement"].casefold()
                    ]
                    if rationale_unknowns:
                        failures.append(
                            f"{sid}: must_not_be_unknown violated; "
                            f"has {len(rationale_unknowns)} unknown-rationale finding(s)"
                        )

                if expected.get("must_report_unknown_rationale"):
                    has_unknown = any(
                        "rationale" in f["statement"].casefold()
                        for f in report["findings"]["unknown"]
                    )
                    if not has_unknown:
                        failures.append(
                            f"{sid}: expected unknown-rationale finding but none present"
                        )

                if "must_include_any" in expected:
                    found = any(
                        s.casefold() in all_text.casefold()
                        for s in expected["must_include_any"]
                    )
                    if not found:
                        failures.append(
                            f"{sid}: must_include_any {expected['must_include_any']!r} "
                            f"— none of these strings appear in the JSON report"
                        )

            except InspectionError as exc:
                if "error_code" not in expected:
                    failures.append(
                        f"{sid}: unexpected InspectionError {exc.code!r}: {exc.message}"
                    )
            except Exception as exc:
                failures.append(f"{sid}: unexpected {type(exc).__name__}: {exc}")

        self.assertFalse(
            failures,
            msg="Benchmark scenario failures:\n" + "\n".join(f"  - {f}" for f in failures),
        )


if __name__ == "__main__":
    unittest.main()
